### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by Jenselme** [AStoker/Aurelia-TDD#1]
Hi,

First of all, thanks for this project. I was able to adapt my karma configuration to run tests on source thanks to it.

My problem is that I experience slowness:
- after `Finished 'createLoaderConfig'`, I have to wait several seconds before the tests actually launch (not a big deal)
- More importantly, after I modified a file, I need to wait between 5 and 7 seconds before the tests are run again. If I run on the bundle, it only takes about 2 seconds. This is not really noticeable on your small test app.

I don't know why these slowness occurs. Do you have a hit?

You can view my current work here: https://github.com/arenaoftitans/arena-of-titans/commit/2a275f2e3a71132e30359d1a50a7da6580c243b0

**Comment by AStoker** [comment]
Yup, I know exactly what you're experiencing. Because things aren't being bundled into a single file, Karma needs to watch _all_ the `node_modules`, since it doesn't know which ones it's going to need. If you have a ton of them, it will take a long time. However, I just thought of a solution for this while I was at dinner the other night (nothing like a full stomach to get the brain going). We have the require config needed to determine the node modules we use before karma runs. So we should be able to parse out the `paths` from that config and determine specifically what we need. I'm gonna be working on that today, I'll let you know how it goes.

**Comment by AStoker** [comment]
Take a look at how I read the config and outputted the used external files. Depending on your production setup, you might have to tweak how you trim down your dependencies. But that should give you a general idea, and improves the start time significantly @Jenselme

**Comment by Jenselme** [comment]
I had to change `project.platform.output` into `project.build.targets[0].output` in test.js to make it work. However, I still have slowness issues. As far as I can tell, your changes had no effect.

> Because things aren't being bundled into a single file, Karma needs to watch all the node_modules, since it doesn't know which ones it's going to need.

But before we configured it not to watch them, didn't we?

**Comment by AStoker** [comment]
Not to watch them, yes. But Karma would still go in and evaluate them all. In regards to your output folder though, yes, that can change depending on your system setup. Glad you got that working. But the slowness is still there?
How slow are we talking? Can you give me your aurelia.json file and your karma configuration file?

**Comment by Jenselme** [comment]
Same as before: 5-7 seconds.
- aurelia.json: https://github.com/arenaoftitans/arena-of-titans/blob/tdd/aurelia_project/aurelia.json
- karma.config.js: https://github.com/arenaoftitans/arena-of-titans/blob/tdd/karma.conf.js

**Comment by AStoker** [comment]
5-7 seconds to start up? That's normal actually. In large scale production setups, we're talking like 5-15 minutes to start up as Karma is analyzing thousands of dependencies and files.

**Comment by Jenselme** [comment]
There 5-7 seconds to start up but that's not an issue. My problem is I also have 5-7 seconds before the tests are launched again. I expected something instantaneous (or at least faster than launching them on the bundles).

**Comment by AStoker** [comment]
There is a delay to get the tests started due to the build process that's needed to trace dependencies and create the proper requirejs config needed. If you have generated that config once, you could put a file check/hash check to see if you need to generate it again, and if you don't have to make it, then don't. That'll save you another 7 seconds. But Karma does not launch instantly. Any faster speeds you want there will have to be addressed there.

**Comment by Jenselme** [comment]
> But Karma does not launch instantly.

It takes a little time to start the first time, but in TDD, it stays up once started. So karma startup time isn't an issue for me.

> If you have generated that config once, you could put a file check/hash check to see if you need to generate it again, and if you don't have to make it, then don't.

I'll see what I can to with this. I'll post an answer here if I manage to get it working.

**Comment by AStoker** [comment]
Perhaps I'm not understanding where your time problem is happening. Where _exactly_ are you experiencing your 5-7 delay, and what is going on when you have that delay?

**Comment by Jenselme** [comment]
Here is a screenshot that may make things clearer.

![aurelia-tdd](https://cloud.githubusercontent.com/assets/6643536/19528384/1542edec-962c-11e6-8e8c-8ed6bed79fa7.png)

**Comment by AStoker** [comment]
Okay, gotcha. So at that point it's Karma that's behaving slowly. Part of the problem is that Babel needs to transpile each file on the fly that it loads up. That takes longer than if you had a single bundle that was pre-transpiled. Additionally, not sure if having multiple browsers testing at the same time slows it down or not.

**Comment by Jenselme** [comment]
> not sure if having multiple browsers testing at the same time slows it down or not.

It faster with only one browser. In this case, I only have a 3-4 seconds delay.

> So at that point it's Karma that's behaving slowly. Part of the problem is that Babel needs to transpile each file on the fly that it loads up.

I'll guess I'll have to find a way to improve that.
